packages:
  - pkgs/*
  - apps/*
  - internal/*
  - scripts/*

catalog:
  vue: ^3.5.13
  vue-router: ^4.5.1
  vue-tsc: 2.2.10
  vue-eslint-parser: ^10.1.3
  vee-validate: ^4.14.7
  zod: ^4
  '@vee-validate/zod': ^4.15.1
  '@vueuse/core': ^13.2.0
  maska: ^3.1.1
  '@tanstack/vue-query': ^5.62.7
  pinia: ^3.0.2
  vite: ^6.3.4
  unbuild: ^3.5.0
  turbo: ^2.5.2
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.3
  vite-plugin-lazy-import: ^1.0.7
  '@vitejs/plugin-vue': ^5.2.3
  '@vitejs/plugin-vue-jsx': ^4.1.2
  rollup: ^4.40.1
  rollup-plugin-visualizer: ^5.14.0
  oxlint: ^0.16.10
  globals: ^16.0.0
  sass: ^1.87.0
  '@clack/prompts': ^0.10.1
  chalk: ^5.4.1
  dayjs: ^1.11.13
  consola: ^3.4.2
  ora: ^8.2.0
  cac: ^6.7.14
  execa: ^9.5.2
  dotenv: ^16.5.0
  find-up: ^7.0.0
  pkg-types: ^2.1.0
  rimraf: ^6.0.1
  prettier: ^3.5.3
  prettier-plugin-tailwindcss: ^0.6.11
  tailwindcss: 4.1.7
  '@tailwindcss/vite': 4.1.7
  '@ast-grep/napi': ^0.37.0
  '@manypkg/get-packages': ^3.0.0
  '@types/node': ^22.15.3
  '@types/eslint': ^9.6.1
  typescript: ^5.8.3
  '@typescript-eslint/eslint-plugin': ^8.31.1
  '@typescript-eslint/parser': ^8.31.1
  '@pnpm/workspace.read-manifest': ^1000.1.4
  resolve.exports: ^2.0.3
  eslint: ^9.26.0
  '@eslint/js': ^9.26.0
  jsonc-eslint-parser: ^2.4.0
  eslint-plugin-oxlint: ^0.16.0
  eslint-plugin-command: ^3.2.0
  eslint-plugin-vue: ^10.1.0
  eslint-plugin-unicorn: ^59.0.0
  eslint-plugin-n: ^17.17.0
  eslint-plugin-jsdoc: ^50.6.11
  eslint-plugin-jsonc: ^2.20.0
  eslint-plugin-perfectionist: ^4.12.3
  eslint-plugin-prettier: ^5.2.6
  eslint-config-turbo: ^2.5.2
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-import-x: ^4.11.0
